server:
  port: 7788
  servlet:
    context-path: /demo

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testDemo?serverTimezone=UTC
    username: root
    password: ok
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zb.demo.entity
  configuration:
    auto-mapping-behavior: full